# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: Npm@1
  inputs:
    command: 'install'

- script: npm test
  displayName: 'Run Tests'

- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'
    failTaskOnFailedTests: true

- script: npx gatsby build
  displayName: 'Run Gatsby build'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: 'public'

